version: '3'
services:
  container1:
    image: ubuntu
    build: .
    networks:
      - containerlink
    ports:
      - "2201:22"

  container2:
    image: ubuntu
    build: .
    networks:
      - containerlink
    ports:
      - "2202:22"

networks:
  containerlink: